/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: 0df167ffb95c7249fc5326180769ae44)
declare namespace Cloudflare {
	interface Env {
		PAGEDATA_CACHE: KVNamespace;
		STATIC_CACHE: KVNamespace;
		GH_OWNER: string;
		GH_REPO: string;
		GH_BRANCH: string;
		GH_PATH: string;
		GH_PAT: string;
		IMAGE_KEY: string;
		DEV_CONTENT_DIR: string;
		GH_TEST: string;
		IMAGES: R2Bucket;
	}
}
interface Env extends Cloudflare.Env {}
